# data and results  
model_name: "LaSSL"
root: "../data/cifar10"
results: "./results"
checkpoint: ""
workers: 0
gpu_ids: 0 # 0,1,2


####################
# 1. train options
####################
seed: 5
n_epoches: 1024 # 512, 1024
n_imgs_per_epoch: 65536 # 64 * 1024
batchsize: 64
mu: 7
print_freq: 128
# optimizer and lr
lr: 0.03
weight_decay: 0.0005 #5e-4
momentum: 0.9


####################
# 2. data and model
####################
# dataset
dataset: "CIFAR10"  # cifar10, cifar100, svhn
n_classes: 10     # 10, 100, 10
n_labeled: 40

# model options
wresnet_k: 2
wresnet_n: 28
use_ema_model: True
ema_m: 0.999


########################
# 3. weights of losses
########################
lambda_semi: 1.0
threshold: 0.95
lambda_cont: 1.0
rampdown_fix_len: 30
rampdown_delta: 1.0
rampdown_lpa_thr: 0.3
rampdown_cacl_thr: 0.1


########################
# 4. CACL
########################
low_dim: 64
temperature: 0.2
contrast_th: 0.8


########################
# 5. BLPA
########################

blpa_join_early: True
blpa_join_later: True

lpa_alpha: 0.8
lpa_topk: 15 # 1.5 * n_classes

use_buffer_bootstrap: True
bootstrap_thred: 0.98
bootstrap_nums: 7 # 5, 7, 9
bootstrap_ratio: 0.8

embedding_pseudo_ratio: 0.2
lpa_ramp_down: False


########################
# 6. MDA and augs
########################
mda_hist_mom: 0.99  #0.99, 0.999 
label_aug: "self_weak" # self, self_weak
unlabel_aug: "semi"


########################
# 7. alation study
######################## 
MDA: True
CACL: True
BLPA: True
# if CACL is false, blpa will be false.
